#!/bin/sh

# Logueamos el arranque
start() {

}

# Logueamos la parada. Tenemos que ver si ha sido checker o manual
stop() {

}

case "$1" in
    start) start;;
    stop) stop;;
    *)
        echo $"Usage: $0 {start|stop}"
        exit 1
esac
exit 0
