#!/bin/sh
### BEGIN INIT INFO
# Provides:          checker
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Checker power logger
# Description:       Logs power on, automatic and manual shutdowns online
### END INIT INFO

CHECKER_DIR="/usr/local/bin/checker"
LOG_FILE="/tmp/checker.log"
LOCKFILE="/var/lock/subsys/checker"

# Logueamos el arranque
start() {
    . $CHECKER_DIR/log.sh "encendido"
    touch $LOCKFILE
}

# Logueamos la parada. Tenemos que ver si ha sido checker o manual
stop() {
    # Si hay algún contenido en /tmp/checker.log
    # entonces es apagado automático
    mensaje="manual"
    if [ -f "$LOG_FILE" ]; then
        automatico=`tail -1 $LOG_FILE`

        echo $automatico
        if [[ -n "${automatico/[ ]*\n/}" ]]; then
            mensaje="automatico"
        fi
    fi
    . $CHECKER_DIR/log.sh $mensaje
    rm -f $LOCKFILE
}

case "$1" in
    start) start;;
    stop) stop;;
    *)
        echo $"Usage: $0 {start|stop}"
        exit 1
esac
exit 0
