#!/bin/sh

CHECKER_DIR="/usr/local/bin/checker"
LOG_FILE="/tmp/checker.log"

# Logueamos el arranque
start() {
    . $CHECKER_DIR/log.sh "encendido"
}

# Logueamos la parada. Tenemos que ver si ha sido checker o manual
stop() {
    # Si hay algún contenido en /tmp/checker.log
    # entonces es apagado automático
    mensaje="manual"
    if [ -f "$LOG_FILE" ]; then
        automatico=`tail -1 $LOG_FILE`

        echo $automatico
        if [[ -n "${automatico/[ ]*\n/}" ]]; then
            mensaje="automatico"
        fi
    fi
    . $CHECKER_DIR/log.sh $mensaje
}

case "$1" in
    start) start;;
    stop) stop;;
    *)
        echo $"Usage: $0 {start|stop}"
        exit 1
esac
exit 0
