#!/bin/sh
### BEGIN INIT INFO
# Provides:          checker
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Checker power logger
# Description:       Logs power on, automatic and manual shutdowns online
### END INIT INFO

. /lib/init/vars.sh
. /lib/lsb/init-functions

PATH=/sbin:/bin:/usr/sbin:/usr/bin

CHECKER_DIR="/usr/local/bin/checker"
LOG_FILE="/tmp/checker.log"
PIDFILE="/var/run/checker.pid"

# Logueamos el arranque
start() {
    $CHECKER_DIR/log.sh "encendido_initd"
    touch $PIDFILE
    exit 0
}

# Logueamos la parada. Tenemos que ver si ha sido checker o manual
stop() {
    # Si hay algún contenido en /tmp/checker.log
    # entonces es apagado automático
    mensaje="apagado_manual_initd"
    if [ -s $LOG_FILE ]; then
        mensaje="apagado_automatico_initd"
    fi
    $CHECKER_DIR/log.sh $mensaje
    /bin/rm -rf $PIDFILE
    exit 0
}

status() {
    if [ -e $PIDFILE ]; then
        log_success_msg "Checker arrancado."
        exit 0
    else
        log_warning_msg "Checker parado."
        exit 3
    fi
}

case "$1" in
    start) start;;
    stop) stop;;
    status) status;;
    *)
        echo $"Usage: $0 {start|stop|status}"
        exit 1
esac
exit 0
